version: '3.8'

services:
  eidolon-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./resources:/bound_resources
    command: /bound_resources/ -m local_dev --reload

  eidolon-webui:
    image: eidolonai/webui:latest
    environment:
      - NEXTAUTH_SECRET=secret
      - EIDOLON_SERVER=http://eidolon-server:8080
    ports:
      - "3000:3000"
    depends_on:
      - eidolon-server