name: Start Server
description: Start agent server and check it is running

runs:
  using: 'composite'
  steps:
    - name: start server
      shell: bash
      run: yes TESTVALUE | make docker-serve Args="--detach"
    - name: check server is running
      shell: bash
      run: |
        start_time=$(date +%s)
        timeout=300  # 5 minutes in seconds
        
        while true; do
          current_time=$(date +%s)
          elapsed=$((current_time - start_time))
          
          response=$(curl -sS -X GET 'http://localhost:8080/system/health' -H 'accept: application/json' -o /dev/null -w "%{http_code}")
          if [ "$response" = "200" ]; then
            echo "Server is up and running"
            exit 0
          fi
        
          if [ $elapsed -ge $timeout ]; then
            echo "Timeout reached. Server did not respond within 5 minutes."
            exit 1
          fi