name: Test

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

jobs:
  test-start-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: test
        uses: ./.github/start-server
